name: CI-Pipeline

on:
  push: 
    branches: [ main ]

jobs: 
  build:
    runs-on: ubuntu-latest
  steps: 
    - name: CheckoutCode
      uses: actions/Checkout@v1
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm tests